import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Globals/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`w-full h-full flex flex-col`}
        suppressHydrationWarning
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
